<a href="https://colab.research.google.com/github/prajapatipiyush1209/Implementation-of-ML-Learning/blob/main/Naive_Bais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Titanic.csv")

In [ ]:
df.head()

      sex   age  sibsp  parch     fare embarked  class    who  alone  survived
0    male  22.0      1      0   7.2500        S  Third    man  False         0
1  female  38.0      1      0  71.2833        C  First  woman  False         1
2  female  26.0      0      0   7.9250        S  Third  woman   True         1
3  female  35.0      1      0  53.1000        S  First  woman  False         1
4    male  35.0      0      0   8.0500        S  Third    man   True         0

In [ ]:
#Drop some columns that need to help
df.drop(["sibsp","parch","embarked"],inplace=True,axis = 1)

In [ ]:
df.head()

      sex   age     fare  class    who  alone  survived
0    male  22.0   7.2500  Third    man  False         0
1  female  38.0  71.2833  First  woman  False         1
2  female  26.0   7.9250  Third  woman   True         1
3  female  35.0  53.1000  First  woman  False         1
4    male  35.0   8.0500  Third    man   True         0

In [ ]:
#Now feature encoding part in the program
dummies = pd.get_dummies(df.sex,drop_first=True)

In [ ]:
dummies

     male
0       1
1       0
2       0
3       0
4       1
..    ...
886     1
887     0
888     0
889     1
890     1

[891 rows x 1 columns]

In [ ]:
df = pd.concat([dummies,df],axis = 1)

In [ ]:
df.drop("sex",inplace=True,axis = 1)

In [ ]:
df.head()

   male   age     fare  class    who  alone  survived
0     1  22.0   7.2500  Third    man  False         0
1     0  38.0  71.2833  First  woman  False         1
2     0  26.0   7.9250  Third  woman   True         1
3     0  35.0  53.1000  First  woman  False         1
4     1  35.0   8.0500  Third    man   True         0

In [ ]:
#Label encoding
df["class"] = df["class"].map({"First": 1, "Second": 2, "Third":3})

In [ ]:
df.head()

   male   age     fare  class    who  alone  survived
0     1  22.0   7.2500      3    man  False         0
1     0  38.0  71.2833      1  woman  False         1
2     0  26.0   7.9250      3  woman   True         1
3     0  35.0  53.1000      1  woman  False         1
4     1  35.0   8.0500      3    man   True         0

In [ ]:
#Now One hot encoding
dummies = pd.get_dummies(df.who,drop_first=True)

In [ ]:
df = pd.concat([dummies,df],axis = 1)

In [ ]:
df.head()

   man  woman  male   age     fare  class    who  alone  survived
0    1      0     1  22.0   7.2500      3    man  False         0
1    0      1     0  38.0  71.2833      1  woman  False         1
2    0      1     0  26.0   7.9250      3  woman   True         1
3    0      1     0  35.0  53.1000      1  woman  False         1
4    1      0     1  35.0   8.0500      3    man   True         0

In [ ]:
df.drop("alone",axis =1, inplace =True)

In [ ]:
df.head()

   man  woman  male   age     fare  class    who  survived
0    1      0     1  22.0   7.2500      3    man         0
1    0      1     0  38.0  71.2833      1  woman         1
2    0      1     0  26.0   7.9250      3  woman         1
3    0      1     0  35.0  53.1000      1  woman         1
4    1      0     1  35.0   8.0500      3    man         0

In [ ]:
df.isnull().sum()

man           0
woman         0
male          0
age         177
fare          0
class         0
who           0
survived      0
dtype: int64

In [ ]:
df["age"]= df.age.fillna(df.age.mean())

In [ ]:
df.drop(["who"],axis = 1, inplace = True)

In [ ]:
# Now Train test split
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
X_train

     man  woman  male        age      fare  class
331    1      0     1  45.500000   28.5000      1
733    1      0     1  23.000000   13.0000      2
382    1      0     1  32.000000    7.9250      3
704    1      0     1  26.000000    7.8542      3
813    0      0     0   6.000000   31.2750      3
..   ...    ...   ...        ...       ...    ...
106    0      1     0  21.000000    7.6500      3
270    1      0     1  29.699118   31.0000      1
860    1      0     1  41.000000   14.1083      3
435    0      0     0  14.000000  120.0000      1
102    1      0     1  21.000000   77.2875      1

[712 rows x 6 columns]

In [ ]:
X.columns = X.columns.astype(str)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
predict_data = classifier.predict(X_test)

In [ ]:
predict_data

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predict_data)
print(f"Accuracy: {accuracy}")

Accuracy: 0.776536312849162

In [ ]:
result = classifier.predict([[0.0,1.0,0.0,35.0,53.1,1.0]])
if result[0] == 0:
  print("Not survied")
else :
  print("Survied")

Survied

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(